# Generated by Django 5.2.14 on 2026-05-19 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_notificationpreference_email_invitation_received_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='email_dispute_message_received',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='email_dispute_received',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='email_dispute_status_update',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='insite_dispute_message_received',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='insite_dispute_received',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='insite_dispute_status_update',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('proposal_received', 'New Proposal'), ('proposal_accepted', 'Proposal Accepted'), ('proposal_rejected', 'Proposal Rejected'), ('progress_update', 'Progress Update'), ('comment_added', 'New Feedback'), ('completion_requested', 'Completion Requested'), ('completion_confirmed', 'Project Completed'), ('completion_rejected', 'Completion Sent Back'), ('message_received', 'New Message'), ('report_received', 'New Report'), ('report_status_update', 'Report Update'), ('invitation_received', 'Project Invitation'), ('dispute_received', 'New Dispute'), ('dispute_message_received', 'New Dispute Message'), ('dispute_status_update', 'Dispute Update')], max_length=30),
        ),
    ]
