<<<<<<< HEAD
# Generated by Django 5.2.14 on 2026-05-18 16:35
=======
# Generated by Django 5.2.14 on 2026-05-18 20:08
>>>>>>> 534edbbef4a3c71ccd5dff8bb906f77b00f60f8e

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_merge_20260518_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artisanprofile',
            name='avatar',
            field=models.ImageField(default='images/avatars/default_avatar.png', upload_to='images/avatars/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='images/avatars/default_avatar.png', upload_to='images/avatars/'),
        ),
    ]
